/* gethistorico */
SELECT O.ID, O.OPERACION, O.TABLA, K.CAMPO, K.VALOR, NULL NEW_VALUE FROM DK$OPERATIONLOG O INNER JOIN DK$KEYLOG K ON O.ID=K.OPER_ID WHERE O.OPERACION<>2 UNION SELECT OP.ID, OP.OPERACION, OP.TABLA, C.CAMPO, C.OLD_VALUE, C.NEW_VALUE VALOR FROM DK$OPERATIONLOG OP INNER JOIN DK$COLUMNLOG C ON OP.ID=C.OPER_ID WHERE OP.OPERACION<>0 ORDER BY 1 ASC

DELETE FROM DK$OPERATIONLOG;

/* COMBINACION EXIST */
SELECT CODARTICULO FROM VENTA WHERE CODARTICULO='066420326205' AND CODCARACT=3 AND VALORCARACT='L' AND CODTARIFA IS NULL UNION SELECT CODARTICULO FROM CAREXIST WHERE CODARTICULO='066420326205' AND CODCARACT=3 AND VALOR='L' UNION SELECT CODCARACT FROM CARVALIDFOTO WHERE CODARTICULO='066420326205' AND CODCARACT=3 AND VALORCARACT='L'

/* SQLFEATURES */
SELECT IC.NOMBRE IDCARACT, ICV.VALORTRADUC IDFEATURE, C.CODCARACT, C.VALOR 
FROM CARVALOR C, IDIOMACARACT IC, IDIOMACARVALID ICV 
WHERE 
C.CODCLASE=ICV.CODCLASE AND 
C.CODCARACT=ICV.CODCARACT AND 
C.VALOR=ICV.VALORCARVALID AND 
IC.CODIDIOMA=ICV.CODIDIOMA AND 
IC.CODCLASE=ICV.CODCLASE AND 
IC.CODCARACT=ICV.CODCARACT AND 
ICV.CODIDIOMA=1 AND 
ICV.CODCLASE=2 AND 
C.CODOBJETO='066420326205' 
ORDER BY IDCARACT ASC, IDFEATURE ASC

/* SQLFIESTAEVENTO */
SELECT IT.DESCRIPCION ID FROM IDIOMATIPO IT, IDIOMACARVALID ICV, CARVALOR CV WHERE CV.VALOR=ICV.VALORCARVALID AND ICV.CODCLASE=CV.CODCLASE AND ICV.CODOBJETO IS NULL AND ICV.CODCARACT=CV.CODCARACT AND ICV.DIMENSION IS NULL AND ICV.VALORTRADUC=IT.METATITLE AND IT.CODIDIOMA=ICV.CODIDIOMA AND CV.CODCLASE=2 AND CV.CODOBJETO='02' AND ICV.CODIDIOMA='1' AND IT.TIPO=13

/* SQLFAMILIA */
SELECT IT.DESCRIPCION ID FROM ARTICULO A INNER JOIN IDIOMATIPO IT ON A.CODFAMILIA=IT.CODTIPO AND IT.CODIDIOMA='1' AND IT.TIPO=13 WHERE A.CODIGO='017535870084'

/* SQLGET COMBINACIONDAO */
SELECT CODCARACT, VALORCARACT FROM VENTA WHERE CODARTICULO='02' AND CODTARIFA IS NULL UNION SELECT CODCARACT, VALOR VALORCARACT FROM CAREXIST WHERE CODARTICULO='02' UNION SELECT CODCARACT, VALORCARACT FROM CARVALIDFOTO WHERE CODARTICULO='02' ORDER BY 1 ASC